// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplicationCoreGLSID.Models;

#nullable disable

namespace WebApplicationCoreGLSID.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230405093840_AddPropertiesToProduit")]
    partial class AddPropertiesToProduit
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProduitSousCategorie", b =>
                {
                    b.Property<Guid>("SousCategorieId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("produitsId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("SousCategorieId", "produitsId");

                    b.HasIndex("produitsId");

                    b.ToTable("ProduitSsCategs", (string)null);
                });

            modelBuilder.Entity("WebApplicationCoreGLSID.Models.Categorie", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("A");

                    b.HasKey("Id");

                    b.ToTable("Categs", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("44cfbfd8-dbc8-4698-a9ed-2f2ffa1956dd"),
                            Name = "Test"
                        },
                        new
                        {
                            Id = new Guid("19081e90-a19f-42d0-a6d4-be095dac327e"),
                            Name = "TestFromSeedDataJson"
                        });
                });

            modelBuilder.Entity("WebApplicationCoreGLSID.Models.ImageProduit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("Image")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<Guid?>("produitId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("produitId");

                    b.ToTable("Images");
                });

            modelBuilder.Entity("WebApplicationCoreGLSID.Models.Produit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DateAjoutProduit")
                        .HasColumnType("datetime2");

                    b.Property<string>("FileName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("produits");
                });

            modelBuilder.Entity("WebApplicationCoreGLSID.Models.SousCategorie", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("SSCatName");

                    b.Property<Guid>("categorieId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("categorieId");

                    b.ToTable("sscategories");
                });

            modelBuilder.Entity("ProduitSousCategorie", b =>
                {
                    b.HasOne("WebApplicationCoreGLSID.Models.SousCategorie", null)
                        .WithMany()
                        .HasForeignKey("SousCategorieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApplicationCoreGLSID.Models.Produit", null)
                        .WithMany()
                        .HasForeignKey("produitsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WebApplicationCoreGLSID.Models.ImageProduit", b =>
                {
                    b.HasOne("WebApplicationCoreGLSID.Models.Produit", "produit")
                        .WithMany()
                        .HasForeignKey("produitId");

                    b.Navigation("produit");
                });

            modelBuilder.Entity("WebApplicationCoreGLSID.Models.SousCategorie", b =>
                {
                    b.HasOne("WebApplicationCoreGLSID.Models.Categorie", "categorie")
                        .WithMany()
                        .HasForeignKey("categorieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("categorie");
                });
#pragma warning restore 612, 618
        }
    }
}
